#ifndef __SCHEDULING_MACROS_H__
#define __SCHEDULING_MACROS_H__

#undef MASTER_MAX_SLOTFRAMES
#define MASTER_MAX_SLOTFRAMES 24
#undef TSCH_SCHEDULE_CONF_MAX_LINKS
#define TSCH_SCHEDULE_CONF_MAX_LINKS 39

#endif